# Generated by Django 6.0.7 on 2026-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0002_user_is_verifyed_alter_user_role"),
        ("accounts", "0003_user_pending_email"),
    ]

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verifyed",
            field=models.BooleanField(
                default=False, verbose_name="Email verification status"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("supplier", "Supplier"),
                    ("dealership", "Dealership"),
                    ("admin", "Administrator"),
                ],
                default="buyer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Pending Email"
            ),
        ),
    ]
