# Generated by Django 6.0.7 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verifyed",
            field=models.BooleanField(
                default=False, verbose_name="Email verification status"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("supplier", "Supplier"),
                    ("dealership", "Dealership"),
                    ("admin", "Administrator"),
                ],
                default="buyer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
