# Generated by Django 6.0.7 on 2026-07-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_buyer_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyer",
            options={
                "ordering": ["user"],
                "verbose_name": "Buyer",
                "verbose_name_plural": "Buyers",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
