# Generated by Django 6.0.7 on 2026-09-13 13:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_user_is_verifyed_alter_user_role_squashed_0003_user_pending_email",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceTopUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CARD", "Card"), ("CRYPTO", "Crypto")],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Tranaction ID payment system",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDING", max_length=20, verbose_name="Top up status"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_topup",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance top up",
                "verbose_name_plural": "Balance top up",
            },
        ),
    ]
