# Generated by Django 6.0.7 on 2026-09-13 22:51

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("accounts", "0004_balancetopup"),
        ("accounts", "0005_user_balance"),
        ("accounts", "0006_alter_balancetopup_options_and_more"),
    ]

    dependencies = [
        (
            "accounts",
            "0002_user_is_verifyed_alter_user_role_squashed_0003_user_pending_email",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Balance (USD)",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BalanceTopUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CARD", "Card"), ("CRYPTO", "Crypto")],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Tranaction ID payment system",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает оплаты"),
                            ("PROCESSING", "Обрабатывается"),
                            ("COMPLETED", "Завершено"),
                            ("FAILED", "Ошибка"),
                            ("CANCELLED", "Отменено"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Top up status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_topups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_provider_response",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "verbose_name": "Balance top up",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="accounts_ba_user_id_189e09_idx"
                    )
                ],
            },
        ),
    ]
