# Generated by Django 6.0.7 on 2026-09-13 14:24

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_balancetopup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Balance (USD)",
            ),
            preserve_default=False,
        ),
    ]
