# Generated by Django 6.0.7 on 2026-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_balancetopup_squashed_0006_alter_balancetopup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancetopup",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Top up status",
            ),
        ),
    ]
