# Generated by Django 6.0.7 on 2026-09-17 12:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_balancetopup_status"),
        ("deals", "0003_purchasehistory_cost_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("TOP_UP", "Balance Top-up"),
                            ("PURCHASE", "Car Purchase (money out)"),
                            ("SALE", "Car Sale (money in)"),
                            ("REFUND", "Refund"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Entry type",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Balance after"
                    ),
                ),
                (
                    "topup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="accounts.balancetopup",
                        verbose_name="Related top-up",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="deals.transaction",
                        verbose_name="Related transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger entry",
                "verbose_name_plural": "Ledger entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_le_user_id_d440c3_idx",
                    )
                ],
            },
        ),
    ]
