# Generated by Django 6.0.7 on 2026-10-01 22:41

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_ledgerentry_squashed_0009_entry_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Balance (USD)",
            ),
        ),
    ]
