# Generated by Django 6.0.7 on 2026-08-06 14:16

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_squashed_0002_rename_brand_id_carmodel_brand"),
        ("dealers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Supplier name"
                    ),
                ),
                ("country", models.CharField(max_length=56, verbose_name="Country")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Location"
                    ),
                ),
                ("founded_year", models.SmallIntegerField(verbose_name="Founded year")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPromo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Promotion name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Discount percent"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier promotion",
                "verbose_name_plural": "Supplier promotions",
                "ordering": ["supplier", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Base price"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="Stock quantity"),
                ),
                (
                    "car_model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_offers",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier car",
                "verbose_name_plural": "Supplier cars",
                "ordering": ["supplier_id", "car_model_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier_id", "car_model_id"),
                        name="unique_supplier_car_model",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierLoyaltyDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Discount percent"
                    ),
                ),
                (
                    "min_purchases",
                    models.IntegerField(verbose_name="Minimum purchases"),
                ),
                (
                    "dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_discounts",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_discounts",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier loyalty discount",
                "verbose_name_plural": "Supplier loyalty discounts",
                "ordering": ["supplier_id", "dealer_id", "min_purchases"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier_id", "dealer_id"),
                        name="unique_supplier_dealer_discount",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierPromoModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_promo_links",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_models",
                        to="suppliers.supplierpromo",
                        verbose_name="Promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier promotion model",
                "verbose_name_plural": "Supplier promotion models",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promo", "car_model"),
                        name="unique_supplier_promo_car_model",
                    )
                ],
            },
        ),
    ]
