# Generated by Django 6.0.7 on 2026-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suppliercar",
            old_name="car_model_id",
            new_name="car_model",
        ),
        migrations.RenameField(
            model_name="suppliercar",
            old_name="supplier_id",
            new_name="supplier",
        ),
        migrations.RenameField(
            model_name="supplierloyaltydiscount",
            old_name="dealer_id",
            new_name="dealer",
        ),
        migrations.RenameField(
            model_name="supplierloyaltydiscount",
            old_name="supplier_id",
            new_name="supplier",
        ),
    ]
