# Generated by Django 6.0.7 on 2026-08-18 13:03

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealershipSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "best_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Best price (USD)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Best supplier for dealership",
                "verbose_name_plural": "Best suppliers for dealerships",
                "ordering": ["dealer_id", "car_model_id", "best_price"],
            },
        ),
        migrations.CreateModel(
            name="Dealership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Dealership name"
                    ),
                ),
                ("country", models.CharField(max_length=56, verbose_name="Country")),
                (
                    "address",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Address (coordinates)"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Balance (USD)"
                    ),
                ),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealerships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership",
                "verbose_name_plural": "Dealerships",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DealershipInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Quantity in stock"),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sale price (USD)"
                    ),
                ),
                (
                    "car_model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealer_inventory",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car in stock",
                "verbose_name_plural": "Cars in stock",
                "ordering": ["dealer_id", "car_model_id"],
            },
        ),
        migrations.CreateModel(
            name="DealershipPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("micro", "Micro"),
                            ("hatchback", "Hatchback"),
                            ("crossover", "Crossover"),
                            ("sedan", "Sedan"),
                            ("coupe", "Coupe"),
                            ("offroad", "Offroad"),
                            ("sport", "Sport"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                        verbose_name="Body type",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                        ],
                        max_length=20,
                        verbose_name="Fuel type",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("MT", "MT"),
                            ("AT", "AT"),
                            ("CVT", "CVT"),
                            ("iMT", "iMT"),
                            ("AMT", "AMT"),
                        ],
                        max_length=10,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("FWD", "FWD"),
                            ("RWD", "RWD"),
                            ("AWD", "AWD"),
                            ("4WD", "4WD"),
                        ],
                        max_length=10,
                        verbose_name="Drive type",
                    ),
                ),
                ("min_hp", models.SmallIntegerField(verbose_name="Min. horsepower")),
                ("max_hp", models.SmallIntegerField(verbose_name="Max. horsepower")),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Min. price (USD)"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Max. price (USD)"
                    ),
                ),
                (
                    "dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership preference",
                "verbose_name_plural": "Dealership preferences",
                "ordering": ["dealer_id", "body_type"],
            },
        ),
        migrations.CreateModel(
            name="DealershipPromo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Promotion name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Discount percent"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership promotion",
                "verbose_name_plural": "Dealership promotions",
                "ordering": ["dealer", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="DealershipPromoModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dealership_promo_links",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_models",
                        to="dealers.dealershippromo",
                        verbose_name="Promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership promotion model",
                "verbose_name_plural": "Dealership promotion models",
            },
        ),
        migrations.CreateModel(
            name="DealershipSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sale price"
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Discount applied"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sold at"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="accounts.buyer",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership sale",
                "verbose_name_plural": "Dealership sales",
                "ordering": ["-sold_at", "-id"],
            },
        ),
    ]
