# Generated by Django 6.0.7 on 2026-08-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("dealers", "0001_initial"),
        ("deals", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipsale",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="deals.offer",
                verbose_name="Offer",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsale",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="dealers.dealershippromo",
                verbose_name="Dealership promotion",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="car_model_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_suppliers",
                to="cars.carmodel",
                verbose_name="Car model",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="dealer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="best_suppliers",
                to="dealers.dealership",
                verbose_name="Dealership",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="supplier_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_contracts",
                to="suppliers.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershipinventory",
            unique_together={("dealer_id", "car_model_id")},
        ),
        migrations.AlterUniqueTogether(
            name="dealershippreference",
            unique_together={("dealer_id", "body_type", "fuel_type")},
        ),
        migrations.AddConstraint(
            model_name="dealershippromomodel",
            constraint=models.UniqueConstraint(
                fields=("promo", "car_model"), name="unique_dealership_promo_car_model"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershipsupplier",
            unique_together={("dealer_id", "supplier_id", "car_model_id")},
        ),
    ]
