# Generated by Django 6.0.7 on 2026-08-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_squashed_0002_rename_brand_id_carmodel_brand"),
        ("dealers", "0001_initial"),
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipsale",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="deals.offer",
                verbose_name="Offer",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsale",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="dealers.dealershippromo",
                verbose_name="Dealership promotion",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="car_model_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_suppliers",
                to="cars.carmodel",
                verbose_name="Car model",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="dealer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="best_suppliers",
                to="dealers.dealership",
                verbose_name="Dealership",
            ),
        ),
    ]
