# Generated by Django 6.0.7 on 2026-08-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dealers", "0002_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipsupplier",
            name="supplier_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_contracts",
                to="suppliers.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershipinventory",
            unique_together={("dealer_id", "car_model_id")},
        ),
        migrations.AlterUniqueTogether(
            name="dealershippreference",
            unique_together={("dealer_id", "body_type", "fuel_type")},
        ),
        migrations.AddConstraint(
            model_name="dealershippromomodel",
            constraint=models.UniqueConstraint(
                fields=("promo", "car_model"), name="unique_dealership_promo_car_model"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershipsupplier",
            unique_together={("dealer_id", "supplier_id", "car_model_id")},
        ),
    ]
