# Generated by Django 6.0.7 on 2026-09-09 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipinventory",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=django.utils.timezone.now,
                max_digits=12,
                verbose_name="Purchase price",
            ),
            preserve_default=False,
        ),
    ]
