# Generated by Django 6.0.7 on 2026-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0003_dealershipinventory_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealership",
            name="balance",
        ),
    ]
