# Generated by Django 6.0.7 on 2026-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
        ("dealers", "0004_remove_dealership_balance"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dealershipinventory",
            constraint=models.UniqueConstraint(
                fields=("dealer_id", "car_model_id"),
                name="unique_dealer_car_model_inventory",
            ),
        ),
    ]
