# Generated by Django 6.0.7 on 2026-09-29 23:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
        ("dealers", "0005_dealershipinventory_unique_dealer_car_model_inventory"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealershipsupplier",
            name="best_price_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Reason of best price change",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="best_price_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Best price updated at"
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="future_best_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Projected best price (future promos)",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="future_best_price_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date when future best price becomes active",
            ),
        ),
        migrations.AddField(
            model_name="dealershipsupplier",
            name="is_best",
            field=models.BooleanField(
                default=False, verbose_name="Is best supplier for this model"
            ),
        ),
        migrations.CreateModel(
            name="PurchaseLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("run_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "car_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_logs",
                        to="cars.carmodel",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_logs",
                        to="dealers.dealership",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_logs",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase log",
                "verbose_name_plural": "Purchase logs",
                "indexes": [
                    models.Index(
                        fields=["run_id", "created_at"],
                        name="dealers_pur_run_id_4b3f34_idx",
                    ),
                    models.Index(
                        fields=["dealership", "car_model", "created_at"],
                        name="dealers_pur_dealers_4a6c01_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchasePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred cars"),
                            ("demand", "Demand based"),
                        ],
                        max_length=16,
                        verbose_name="Pass type",
                    ),
                ),
                ("slot", models.DateTimeField(verbose_name="Time slot")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Unit price"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Idempotency key"
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_plans",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_plans",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_plans",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase plan",
                "verbose_name_plural": "Purchase plans",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dealership", "car_model", "pass_type", "slot"),
                        name="unique_purchase_plan_per_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierPriceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("run_id", models.UUIDField(db_index=True)),
                (
                    "old_best_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "new_best_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "dealership_supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_logs",
                        to="dealers.dealershipsupplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier price log",
                "verbose_name_plural": "Supplier price logs",
                "indexes": [
                    models.Index(
                        fields=["run_id", "created_at"],
                        name="dealers_sup_run_id_3e89fe_idx",
                    )
                ],
            },
        ),
    ]
