# Generated by Django 6.0.7 on 2026-09-30 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0006_dealershipsupplier_best_price_reason_and_more"),
        ("deals", "0005_offerlog_supplyhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseplan",
            name="offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_plan",
                to="deals.offer",
                verbose_name="Offer",
            ),
        ),
    ]
