# Generated by Django 6.0.7 on 2026-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="accepted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Accepted price",
            ),
        ),
    ]
