# Generated by Django 6.0.7 on 2026-08-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("deals", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="suppliers.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_history",
                to="deals.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["status"], name="deals_offer_status_d86412_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["expires_at"], name="deals_offer_expires_1c0160_idx"
            ),
        ),
    ]
