# Generated by Django 6.0.7 on 2026-09-09 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0002_offer_accepted_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=django.utils.timezone.now,
                max_digits=12,
                verbose_name="Cost price",
            ),
            preserve_default=False,
        ),
    ]
