# Generated by Django 6.0.7 on 2026-09-24 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_entry_transaction_and_more"),
        ("deals", "0003_purchasehistory_cost_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="dealership",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="supplier",
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_history",
                to="accounts.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="deals_offer_status_d86412_idx",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="deals_offer_expires_1c0160_idx",
        ),
        migrations.AddField(
            model_name="offer",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Max price per unit"
            ),
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="accepted_price",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="buyer",
        ),
    ]
