# Generated by Django 6.0.7 on 2026-09-29 23:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_ledgerentry_squashed_0009_entry_transaction_and_more"),
        ("cars", "0001_initial"),
        ("dealers", "0006_dealershipsupplier_best_price_reason_and_more"),
        ("deals", "0004_remove_transaction_buyer_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("run_id", models.UUIDField(db_index=True)),
                ("step", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="deals.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer log",
                "verbose_name_plural": "Offer logs",
                "indexes": [
                    models.Index(
                        fields=["offer", "created_at"],
                        name="deals_offer_offer_i_ba2a35_idx",
                    ),
                    models.Index(
                        fields=["run_id", "created_at"],
                        name="deals_offer_run_id_2cec1c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplyHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Unit price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total price"
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Purchased at"
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_history",
                        to="cars.carmodel",
                        verbose_name="Car model",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_history",
                        to="dealers.dealership",
                        verbose_name="Dealership",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_history",
                        to="deals.offer",
                        verbose_name="Offer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_history",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_history",
                        to="accounts.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply history",
                "verbose_name_plural": "Supply histories",
                "ordering": ["-purchased_at"],
                "indexes": [
                    models.Index(
                        fields=["dealership", "supplier"],
                        name="deals_suppl_dealers_a4419c_idx",
                    )
                ],
            },
        ),
    ]
