# Generated by Django 6.0.7 on 2026-10-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_offerlog_supplyhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
