# Generated by Django 6.0.7 on 2026-08-18 13:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_sales",
                    models.PositiveIntegerField(default=0, verbose_name="Total sales"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total revenue"
                    ),
                ),
                (
                    "unique_buyers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Unique buyers"
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total profit"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Calculated at"),
                ),
            ],
            options={
                "verbose_name": "Sales statistics",
                "verbose_name_plural": "Sales statistics",
            },
        ),
    ]
