# Generated by Django 6.0.7 on 2026-08-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesstatistics",
            name="dealership",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="dealers.dealership",
                verbose_name="Dealership",
            ),
        ),
    ]
