# Generated by Django 6.0.7 on 2026-08-04 14:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("cars", "0001_initial"),
        ("cars", "0002_rename_brand_id_carmodel_brand"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Brand name"
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=56, verbose_name="Country of origin"),
                ),
            ],
            options={
                "verbose_name": "Car brand",
                "verbose_name_plural": "Car brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, verbose_name="Model name")),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("micro", "Micro"),
                            ("hatchback", "Hatchback"),
                            ("crossover", "Crossover"),
                            ("sedan", "Sedan"),
                            ("coupe", "Coupe"),
                            ("offroad", "Offroad"),
                            ("sport", "Sport"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                        verbose_name="Body type",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                        ],
                        max_length=20,
                        verbose_name="Fuel type",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("MT", "MT"),
                            ("AT", "AT"),
                            ("CVT", "CVT"),
                            ("iMT", "iMT"),
                            ("AMT", "AMT"),
                        ],
                        max_length=10,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("FWD", "FWD"),
                            ("RWD", "RWD"),
                            ("AWD", "AWD"),
                            ("4WD", "4WD"),
                        ],
                        max_length=10,
                        verbose_name="Drive type",
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Engine volume"
                    ),
                ),
                (
                    "horsepower",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Horsepower"
                    ),
                ),
                (
                    "year_form",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Production from"
                    ),
                ),
                (
                    "year_to",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Production to"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="cars.carbrand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car model",
                "verbose_name_plural": "Car models",
                "ordering": ["brand_id", "name"],
            },
        ),
    ]
