# Generated by Django 6.0.7 on 2026-07-31 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmodel",
            old_name="brand_id",
            new_name="brand",
        ),
    ]
